# Generated by Django 5.1.3 on 2024-12-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name='usuario')),
                ('contraseña', models.CharField(max_length=50, verbose_name='contraseña')),
            ],
        ),
    ]
