# Generated by Django 5.1.3 on 2024-12-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceApp', '0002_confirmarusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmarUsuario',
        ),
    ]
