# Generated by Django 5.1.3 on 2024-12-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceApp', '0007_direccionesenvio_usuariocliente_delete_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='parent',
        ),
    ]
