# Generated by Django 5.1.3 on 2024-12-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceApp', '0009_alter_productos_imagen_imagenproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariocliente',
            options={'verbose_name': 'Usuario Cliente', 'verbose_name_plural': 'Usuarios Clientes'},
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='Usuarios/'),
        ),
    ]
