# Generated by Django 5.1.3 on 2024-12-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceApp', '0010_alter_usuariocliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='Usuarios/'),
        ),
    ]
