# Generated by Django 5.1.4 on 2024-12-26 22:59

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceApp', '0011_alter_usuariocliente_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionesenvio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuariocliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuariocliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuariocliente',
            name='ultimo_acceso',
        ),
        migrations.AddField(
            model_name='direccionesenvio',
            name='usuario_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL, verbose_name='UsuarioCliente'),
        ),
        migrations.AlterField(
            model_name='direccionesenvio',
            name='es_principal',
            field=models.BooleanField(default=False, verbose_name='Es Principal'),
        ),
        migrations.AlterField(
            model_name='direccionesenvio',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='direccionesenvio',
            name='tipo',
            field=models.CharField(choices=[('envio', 'Envío'), ('facturacion', 'Facturación'), ('trabajo', 'Trabajo')], max_length=50, verbose_name='Tipo de Dirección'),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='direccionesenvio',
            index=models.Index(fields=['usuario_cliente', 'es_principal'], name='EcomerceApp_usuario_6ce37a_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionesenvio',
            index=models.Index(fields=['tipo'], name='EcomerceApp_tipo_15c468_idx'),
        ),
    ]
