# Generated by Django 5.1.4 on 2024-12-27 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceApp', '0012_remove_direccionesenvio_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carrito', to=settings.AUTH_USER_MODEL, verbose_name='Id_Usuario'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carrito', to='EcomerceApp.productos', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DetalleVenta', to='EcomerceApp.productos', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DetalleVenta', to='EcomerceApp.ventas', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='listadeseos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ListaDeseos', to=settings.AUTH_USER_MODEL, verbose_name='Id_Usuario'),
        ),
        migrations.AlterField(
            model_name='listadeseos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ListaDeseos', to='EcomerceApp.productos', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Productos', to='EcomerceApp.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Productos', to='EcomerceApp.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Productos', to='EcomerceApp.proveedores', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stick_Maximo'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ventas', to=settings.AUTH_USER_MODEL, verbose_name='Id_Usuario'),
        ),
    ]
