# Generated by Django 5.1.4 on 2024-12-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomerceApp', '0013_alter_carrito_id_usuario_alter_carrito_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock_Maximo'),
        ),
    ]
